Import the Libraries

In [1]:
import requests
from  bs4 import BeautifulSoup
import csv
import pandas as pd
import time
from urllib.parse import urljoin
import sqlite3

Get URL and send Get request

In [2]:
url= "https://books.toscrape.com/"
response= requests.get(url)
if response.status_code == 200:
    print("Request Successful")
else:
    print("Request Failed")

Request Successful

Parse the HTML Content

In [3]:
soup= BeautifulSoup(response.text, "html.parser")
print(soup)

<!DOCTYPE html>

<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-us"> <!--<![endif]-->
<head>
<title>
    All products | Books to Scrape - Sandbox
</title>
<meta content="text/html; charset=utf-8" http-equiv="content-type"/>
<meta content="24th Jun 2016 09:29" name="created"/>
<meta content="" name="description"/>
<meta content="width=device-width" name="viewport"/>
<meta content="NOARCHIVE,NOCACHE" name="robots"/>
<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
<link href="static/oscar/favicon.ico" rel="shortcut icon"/>
<link href="static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
<link href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
<link href="static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
</head>
<body class="default" id="default">
<header class="header container-fluid">
<div class="page_inner">
<div class="row">
<div class="col-sm-8 h1"><a href="index.html">Books to Scrape</a><small> We love being scraped!</small>
</div>
</div>
</div>
</header>
<div class="container-fluid page">
<div class="page_inner">
<ul class="breadcrumb">
<li>
<a href="index.html">Home</a>
</li>
<li class="active">All products</li>
</ul>
<div class="row">
<aside class="sidebar col-sm-4 col-md-3">
<div id="promotions_left">
</div>
<div class="side_categories">
<ul class="nav nav-list">
<li>
<a href="catalogue/category/books_1/index.html">

                                Books

                        </a>
<ul>
<li>
<a href="catalogue/category/books/travel_2/index.html">

                                Travel

                        </a>
</li>
<li>
<a href="catalogue/category/books/mystery_3/index.html">

                                Mystery

                        </a>
</li>
<li>
<a href="catalogue/category/books/historical-fiction_4/index.html">

                                Historical Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/sequential-art_5/index.html">

                                Sequential Art

                        </a>
</li>
<li>
<a href="catalogue/category/books/classics_6/index.html">

                                Classics

                        </a>
</li>
<li>
<a href="catalogue/category/books/philosophy_7/index.html">

                                Philosophy

                        </a>
</li>
<li>
<a href="catalogue/category/books/romance_8/index.html">

                                Romance

                        </a>
</li>
<li>
<a href="catalogue/category/books/womens-fiction_9/index.html">

                                Womens Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/fiction_10/index.html">

                                Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/childrens_11/index.html">

                                Childrens

                        </a>
</li>
<li>
<a href="catalogue/category/books/religion_12/index.html">

                                Religion

                        </a>
</li>
<li>
<a href="catalogue/category/books/nonfiction_13/index.html">

                                Nonfiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/music_14/index.html">

                                Music

                        </a>
</li>
<li>
<a href="catalogue/category/books/default_15/index.html">

                                Default

                        </a>
</li>
<li>
<a href="catalogue/category/books/science-fiction_16/index.html">

                                Science Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/sports-and-games_17/index.html">

                                Sports and Games

                        </a>
</li>
<li>
<a href="catalogue/category/books/add-a-comment_18/index.html">

                                Add a comment

                        </a>
</li>
<li>
<a href="catalogue/category/books/fantasy_19/index.html">

                                Fantasy

                        </a>
</li>
<li>
<a href="catalogue/category/books/new-adult_20/index.html">

                                New Adult

                        </a>
</li>
<li>
<a href="catalogue/category/books/young-adult_21/index.html">

                                Young Adult

                        </a>
</li>
<li>
<a href="catalogue/category/books/science_22/index.html">

                                Science

                        </a>
</li>
<li>
<a href="catalogue/category/books/poetry_23/index.html">

                                Poetry

                        </a>
</li>
<li>
<a href="catalogue/category/books/paranormal_24/index.html">

                                Paranormal

                        </a>
</li>
<li>
<a href="catalogue/category/books/art_25/index.html">

                                Art

                        </a>
</li>
<li>
<a href="catalogue/category/books/psychology_26/index.html">

                                Psychology

                        </a>
</li>
<li>
<a href="catalogue/category/books/autobiography_27/index.html">

                                Autobiography

                        </a>
</li>
<li>
<a href="catalogue/category/books/parenting_28/index.html">

                                Parenting

                        </a>
</li>
<li>
<a href="catalogue/category/books/adult-fiction_29/index.html">

                                Adult Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/humor_30/index.html">

                                Humor

                        </a>
</li>
<li>
<a href="catalogue/category/books/horror_31/index.html">

                                Horror

                        </a>
</li>
<li>
<a href="catalogue/category/books/history_32/index.html">

                                History

                        </a>
</li>
<li>
<a href="catalogue/category/books/food-and-drink_33/index.html">

                                Food and Drink

                        </a>
</li>
<li>
<a href="catalogue/category/books/christian-fiction_34/index.html">

                                Christian Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/business_35/index.html">

                                Business

                        </a>
</li>
<li>
<a href="catalogue/category/books/biography_36/index.html">

                                Biography

                        </a>
</li>
<li>
<a href="catalogue/category/books/thriller_37/index.html">

                                Thriller

                        </a>
</li>
<li>
<a href="catalogue/category/books/contemporary_38/index.html">

                                Contemporary

                        </a>
</li>
<li>
<a href="catalogue/category/books/spirituality_39/index.html">

                                Spirituality

                        </a>
</li>
<li>
<a href="catalogue/category/books/academic_40/index.html">

                                Academic

                        </a>
</li>
<li>
<a href="catalogue/category/books/self-help_41/index.html">

                                Self Help

                        </a>
</li>
<li>
<a href="catalogue/category/books/historical_42/index.html">

                                Historical

                        </a>
</li>
<li>
<a href="catalogue/category/books/christian_43/index.html">

                                Christian

                        </a>
</li>
<li>
<a href="catalogue/category/books/suspense_44/index.html">

                                Suspense

                        </a>
</li>
<li>
<a href="catalogue/category/books/short-stories_45/index.html">

                                Short Stories

                        </a>
</li>
<li>
<a href="catalogue/category/books/novels_46/index.html">

                                Novels

                        </a>
</li>
<li>
<a href="catalogue/category/books/health_47/index.html">

                                Health

                        </a>
</li>
<li>
<a href="catalogue/category/books/politics_48/index.html">

                                Politics

                        </a>
</li>
<li>
<a href="catalogue/category/books/cultural_49/index.html">

                                Cultural

                        </a>
</li>
<li>
<a href="catalogue/category/books/erotica_50/index.html">

                                Erotica

                        </a>
</li>
<li>
<a href="catalogue/category/books/crime_51/index.html">

                                Crime

                        </a>
</li>
</ul></li>
</ul>
</div>
</aside>
<div class="col-sm-8 col-md-9">
<div class="page-header action">
<h1>All products</h1>
</div>
<div id="messages">
</div>
<div id="promotions">
</div>
<form class="form-horizontal" method="get">
<div style="display:none">
</div>
<strong>1000</strong> results - showing <strong>1</strong> to <strong>20</strong>.




    </form>
<section>
<div class="alert alert-warning" role="alert"><strong>Warning!</strong> This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.</div>
<div>
<ol class="row">
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
<div class="product_price">
<p class="price_color">Â£51.77</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/tipping-the-velvet_999/index.html"><img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">Tipping the Velvet</a></h3>
<div class="product_price">
<p class="price_color">Â£53.74</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/soumission_998/index.html"><img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/soumission_998/index.html" title="Soumission">Soumission</a></h3>
<div class="product_price">
<p class="price_color">Â£50.10</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/sharp-objects_997/index.html"><img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">Sharp Objects</a></h3>
<div class="product_price">
<p class="price_color">Â£47.82</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html"><img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/></a>
</div>
<p class="star-rating Five">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">Sapiens: A Brief History ...</a></h3>
<div class="product_price">
<p class="price_color">Â£54.23</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-requiem-red_995/index.html"><img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">The Requiem Red</a></h3>
<div class="product_price">
<p class="price_color">Â£22.65</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html"><img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">The Dirty Little Secrets ...</a></h3>
<div class="product_price">
<p class="price_color">Â£33.34</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html"><img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html" title="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull">The Coming Woman: A ...</a></h3>
<div class="product_price">
<p class="price_color">Â£17.93</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html"><img alt="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics" class="thumbnail" src="media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html" title="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics">The Boys in the ...</a></h3>
<div class="product_price">
<p class="price_color">Â£22.60</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-black-maria_991/index.html"><img alt="The Black Maria" class="thumbnail" src="media/cache/58/46/5846057e28022268153beff6d352b06c.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-black-maria_991/index.html" title="The Black Maria">The Black Maria</a></h3>
<div class="product_price">
<p class="price_color">Â£52.15</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html"><img alt="Starving Hearts (Triangular Trade Trilogy, #1)" class="thumbnail" src="media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg"/></a>
</div>
<p class="star-rating Two">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html" title="Starving Hearts (Triangular Trade Trilogy, #1)">Starving Hearts (Triangular Trade ...</a></h3>
<div class="product_price">
<p class="price_color">Â£13.99</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">

Extract Book Details for Page 1

In [4]:
#find all 20 Books on page 1
books= soup.find_all('h3')
start_time= time.time()
books_extracted= 0
#Iterate through the books ad extract the information for each book
for book in books:
    book_url= book.find('a')['href']

    #full_book_url = url + book_url
    full_book_url = urljoin(url, book_url)

    book_response= requests.get(url + book_url)
    book_soup= BeautifulSoup(book_response.content, "html.parser")
    title= book_soup.find('h1').text
    category= book_soup.find('ul', class_='breadcrumb').find_all('a')[2].text.strip()
    rating= book_soup.find('p', class_='star-rating')['class'][1]
    price= book_soup.find('p', class_='price_color').text.strip()
    availability= book_soup.find('p', class_='availability').text.strip()
    books_extracted += 1

    end_time=time.time()
    total_time= (end_time - start_time)/60.0

    print(f"Title: {title}")
    print(f"Category: {category}")
    print(f"Rating: {rating}")
    print(f"Price: {price}")
    print(f"Availability: {availability}")
    print(f"Book URL: {full_book_url}")
    print("**************")


print(f"Number of Books Extracted {books_extracted}")
print(f"Total Time : {total_time:.4f} ")

Title: A Light in the Attic
Category: Poetry
Rating: Three
Price: £51.77
Availability: In stock (22 available)
Book URL: https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html
**************
Title: Tipping the Velvet
Category: Historical Fiction
Rating: One
Price: £53.74
Availability: In stock (20 available)
Book URL: https://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html
**************
Title: Soumission
Category: Fiction
Rating: One
Price: £50.10
Availability: In stock (20 available)
Book URL: https://books.toscrape.com/catalogue/soumission_998/index.html
**************
Title: Sharp Objects
Category: Mystery
Rating: Four
Price: £47.82
Availability: In stock (20 available)
Book URL: https://books.toscrape.com/catalogue/sharp-objects_997/index.html
**************
Title: Sapiens: A Brief History of Humankind
Category: History
Rating: Five
Price: £54.23
Availability: In stock (20 available)
Book URL: https://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html
**************
Title: The Requiem Red
Category: Young Adult
Rating: One
Price: £22.65
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/the-requiem-red_995/index.html
**************
Title: The Dirty Little Secrets of Getting Your Dream Job
Category: Business
Rating: Four
Price: £33.34
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html
**************
Title: The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
Category: Default
Rating: Three
Price: £17.93
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html
**************
Title: The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
Category: Default
Rating: Four
Price: £22.60
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html
**************
Title: The Black Maria
Category: Poetry
Rating: One
Price: £52.15
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/the-black-maria_991/index.html
**************
Title: Starving Hearts (Triangular Trade Trilogy, #1)
Category: Default
Rating: Two
Price: £13.99
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html
**************
Title: Shakespeare's Sonnets
Category: Poetry
Rating: Four
Price: £20.66
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html
**************
Title: Set Me Free
Category: Young Adult
Rating: Five
Price: £17.46
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/set-me-free_988/index.html
**************
Title: Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Category: Sequential Art
Rating: Five
Price: £52.29
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html
**************
Title: Rip it Up and Start Again
Category: Music
Rating: Five
Price: £35.02
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html
**************
Title: Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Category: Music
Rating: Three
Price: £57.25
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html
**************
Title: Olio
Category: Poetry
Rating: One
Price: £23.88
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/olio_984/index.html
**************
Title: Mesaerion: The Best Science Fiction Stories 1800-1849
Category: Science Fiction
Rating: One
Price: £37.59
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html
**************
Title: Libertarianism for Beginners
Category: Politics
Rating: Two
Price: £51.33
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html
**************
Title: It's Only the Himalayas
Category: Travel
Rating: Two
Price: £45.17
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html
**************
Number of Books Extracted 20
Total Time : 0.0082

Extract details for all 5 pages

In [5]:
# Create a List to hold all the book information
books_data = []

# Loop through all 5 pages
for page_num in range(1, 6):

    url = f"https://books.toscrape.com/catalogue/page-{page_num}.html"
    response = requests.get(url)
    soup = BeautifulSoup(response.content, "html.parser")

    books = soup.find_all('h3')


    start_time = time.time()

    # Store books for the current page only
    page_books = []

    for book in books:

        book_url = book.find('a')['href']
        full_book_url = urljoin(url, book_url)


        book_response = requests.get(
            'https://books.toscrape.com/catalogue/' + book_url
        )

        book_soup = BeautifulSoup(
            book_response.content, "html.parser"
        )

        title = book_soup.find('h1').text.strip()

        category = (
            book_soup
            .find('ul', class_='breadcrumb')
            .find_all('a')[2]
            .text
            .strip()
        )

        rating = book_soup.find(
            'p', class_='star-rating'
        )['class'][1]

        price = book_soup.find(
            'p', class_='price_color'
        ).text.strip()

        availability = book_soup.find(
            'p', class_='availability'
        ).text.strip()

        book_data = [
            title,
            category,
            rating,
            price,
            availability,
            full_book_url
        ]

        # Add to the main list
        books_data.append(book_data)

        # Add to current page list
        page_books.append(book_data)

    end_time = time.time()

    total_time = (end_time - start_time) / 60.0

    # Print current page data
    print(f"\n========== PAGE {page_num} ==========")

    for i, book_data in enumerate(page_books, start=1):
        print(f"\nBook {i}")
        print(f"Title: {book_data[0]}")
        print(f"Category: {book_data[1]}")
        print(f"Rating: {book_data[2]}")
        print(f"Price: {book_data[3]}")
        print(f"Availability: {book_data[4]}")
        print(f"Book URL: {book_data[5]}")
        print("***********")

    print("\n-----------------------------")
    print(f"Page {page_num} completed.")
    print(f"{len(page_books)} books extracted from this page.")
    print(f"{len(books_data)} books extracted so far.")
    print(f"Time: {total_time:.2f} minutes")
    print("*****************************")

========== PAGE 1 ==========

Book 1
Title: A Light in the Attic
Category: Poetry
Rating: Three
Price: £51.77
Availability: In stock (22 available)
Book URL: https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html
***********

Book 2
Title: Tipping the Velvet
Category: Historical Fiction
Rating: One
Price: £53.74
Availability: In stock (20 available)
Book URL: https://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html
***********

Book 3
Title: Soumission
Category: Fiction
Rating: One
Price: £50.10
Availability: In stock (20 available)
Book URL: https://books.toscrape.com/catalogue/soumission_998/index.html
***********

Book 4
Title: Sharp Objects
Category: Mystery
Rating: Four
Price: £47.82
Availability: In stock (20 available)
Book URL: https://books.toscrape.com/catalogue/sharp-objects_997/index.html
***********

Book 5
Title: Sapiens: A Brief History of Humankind
Category: History
Rating: Five
Price: £54.23
Availability: In stock (20 available)
Book URL: https://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html
***********

Book 6
Title: The Requiem Red
Category: Young Adult
Rating: One
Price: £22.65
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/the-requiem-red_995/index.html
***********

Book 7
Title: The Dirty Little Secrets of Getting Your Dream Job
Category: Business
Rating: Four
Price: £33.34
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html
***********

Book 8
Title: The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
Category: Default
Rating: Three
Price: £17.93
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html
***********

Book 9
Title: The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
Category: Default
Rating: Four
Price: £22.60
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html
***********

Book 10
Title: The Black Maria
Category: Poetry
Rating: One
Price: £52.15
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/the-black-maria_991/index.html
***********

Book 11
Title: Starving Hearts (Triangular Trade Trilogy, #1)
Category: Default
Rating: Two
Price: £13.99
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html
***********

Book 12
Title: Shakespeare's Sonnets
Category: Poetry
Rating: Four
Price: £20.66
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html
***********

Book 13
Title: Set Me Free
Category: Young Adult
Rating: Five
Price: £17.46
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/set-me-free_988/index.html
***********

Book 14
Title: Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Category: Sequential Art
Rating: Five
Price: £52.29
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html
***********

Book 15
Title: Rip it Up and Start Again
Category: Music
Rating: Five
Price: £35.02
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html
***********

Book 16
Title: Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Category: Music
Rating: Three
Price: £57.25
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html
***********

Book 17
Title: Olio
Category: Poetry
Rating: One
Price: £23.88
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/olio_984/index.html
***********

Book 18
Title: Mesaerion: The Best Science Fiction Stories 1800-1849
Category: Science Fiction
Rating: One
Price: £37.59
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html
***********

Book 19
Title: Libertarianism for Beginners
Category: Politics
Rating: Two
Price: £51.33
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html
***********

Book 20
Title: It's Only the Himalayas
Category: Travel
Rating: Two
Price: £45.17
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html
***********

-----------------------------
Page 1 completed.
20 books extracted from this page.
20 books extracted so far.
Time: 0.01 minutes
*****************************

========== PAGE 2 ==========

Book 1
Title: In Her Wake
Category: Thriller
Rating: One
Price: £12.84
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/in-her-wake_980/index.html
***********

Book 2
Title: How Music Works
Category: Music
Rating: Two
Price: £37.32
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/how-music-works_979/index.html
***********

Book 3
Title: Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More
Category: Food and Drink
Rating: Three
Price: £30.52
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html
***********

Book 4
Title: Chase Me (Paris Nights #2)
Category: Romance
Rating: Five
Price: £25.27
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/chase-me-paris-nights-2_977/index.html
***********

Book 5
Title: Black Dust
Category: Romance
Rating: Five
Price: £34.53
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/black-dust_976/index.html
***********

Book 6
Title: Birdsong: A Story in Pictures
Category: Childrens
Rating: Three
Price: £54.64
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/birdsong-a-story-in-pictures_975/index.html
***********

Book 7
Title: America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana
Category: Default
Rating: Three
Price: £22.50
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html
***********

Book 8
Title: Aladdin and His Wonderful Lamp
Category: Default
Rating: Three
Price: £53.13
Availability: In stock (19 available)
Book URL: https://books.toscrape.com/catalogue/aladdin-and-his-wonderful-lamp_973/index.html
***********

Book 9
Title: Worlds Elsewhere: Journeys Around Shakespeare’s Globe
Category: Nonfiction
Rating: Five
Price: £40.30
Availability: In stock (18 available)
Book URL: https://books.toscrape.com/catalogue/worlds-elsewhere-journeys-around-shakespeares-globe_972/index.html
***********

Book 10
Title: Wall and Piece
Category: Art
Rating: Four
Price: £44.18
Availability: In stock (18 available)
Book URL: https://books.toscrape.com/catalogue/wall-and-piece_971/index.html
***********

Book 11
Title: The Four Agreements: A Practical Guide to Personal Freedom
Category: Spirituality
Rating: Five
Price: £17.66
Availability: In stock (18 available)
Book URL: https://books.toscrape.com/catalogue/the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html
***********

Book 12
Title: The Five Love Languages: How to Express Heartfelt Commitment to Your Mate
Category: Nonfiction
Rating: Three
Price: £31.05
Availability: In stock (18 available)
Book URL: https://books.toscrape.com/catalogue/the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969/index.html
***********

Book 13
Title: The Elephant Tree
Category: Thriller
Rating: Five
Price: £23.82
Availability: In stock (18 available)
Book URL: https://books.toscrape.com/catalogue/the-elephant-tree_968/index.html
***********

Book 14
Title: The Bear and the Piano
Category: Childrens
Rating: One
Price: £36.89
Availability: In stock (18 available)
Book URL: https://books.toscrape.com/catalogue/the-bear-and-the-piano_967/index.html
***********

Book 15
Title: Sophie's World
Category: Philosophy
Rating: Five
Price: £15.94
Availability: In stock (18 available)
Book URL: https://books.toscrape.com/catalogue/sophies-world_966/index.html
***********

Book 16
Title: Penny Maybe
Category: Default
Rating: Three
Price: £33.29
Availability: In stock (18 available)
Book URL: https://books.toscrape.com/catalogue/penny-maybe_965/index.html
***********

Book 17
Title: Maude (1883-1993):She Grew Up with the country
Category: Default
Rating: Two
Price: £18.02
Availability: In stock (18 available)
Book URL: https://books.toscrape.com/catalogue/maude-1883-1993she-grew-up-with-the-country_964/index.html
***********

Book 18
Title: In a Dark, Dark Wood
Category: Mystery
Rating: One
Price: £19.63
Availability: In stock (18 available)
Book URL: https://books.toscrape.com/catalogue/in-a-dark-dark-wood_963/index.html
***********

Book 19
Title: Behind Closed Doors
Category: Thriller
Rating: Four
Price: £52.22
Availability: In stock (18 available)
Book URL: https://books.toscrape.com/catalogue/behind-closed-doors_962/index.html
***********

Book 20
Title: You can't bury them all: Poems
Category: Poetry
Rating: Two
Price: £33.63
Availability: In stock (17 available)
Book URL: https://books.toscrape.com/catalogue/you-cant-bury-them-all-poems_961/index.html
***********

-----------------------------
Page 2 completed.
20 books extracted from this page.
40 books extracted so far.
Time: 0.01 minutes
*****************************

========== PAGE 3 ==========

Book 1
Title: Slow States of Collapse: Poems
Category: Poetry
Rating: Three
Price: £57.31
Availability: In stock (17 available)
Book URL: https://books.toscrape.com/catalogue/slow-states-of-collapse-poems_960/index.html
***********

Book 2
Title: Reasons to Stay Alive
Category: Nonfiction
Rating: Two
Price: £26.41
Availability: In stock (17 available)
Book URL: https://books.toscrape.com/catalogue/reasons-to-stay-alive_959/index.html
***********

Book 3
Title: Private Paris (Private #10)
Category: Fiction
Rating: Five
Price: £47.61
Availability: In stock (17 available)
Book URL: https://books.toscrape.com/catalogue/private-paris-private-10_958/index.html
***********

Book 4
Title: #HigherSelfie: Wake Up Your Life. Free Your Soul. Find Your Tribe.
Category: Nonfiction
Rating: Five
Price: £23.11
Availability: In stock (17 available)
Book URL: https://books.toscrape.com/catalogue/higherselfie-wake-up-your-life-free-your-soul-find-your-tribe_957/index.html
***********

Book 5
Title: Without Borders (Wanderlove #1)
Category: New Adult
Rating: Two
Price: £45.07
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/without-borders-wanderlove-1_956/index.html
***********

Book 6
Title: When We Collided
Category: Contemporary
Rating: One
Price: £31.77
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/when-we-collided_955/index.html
***********

Book 7
Title: We Love You, Charlie Freeman
Category: Fiction
Rating: Five
Price: £50.27
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/we-love-you-charlie-freeman_954/index.html
***********

Book 8
Title: Untitled Collection: Sabbath Poems 2014
Category: Poetry
Rating: Four
Price: £14.27
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/untitled-collection-sabbath-poems-2014_953/index.html
***********

Book 9
Title: Unseen City: The Majesty of Pigeons, the Discreet Charm of Snails & Other Wonders of the Urban Wilderness
Category: Nonfiction
Rating: Four
Price: £44.18
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/unseen-city-the-majesty-of-pigeons-the-discreet-charm-of-snails-other-wonders-of-the-urban-wilderness_952/index.html
***********

Book 10
Title: Unicorn Tracks
Category: Fantasy
Rating: Three
Price: £18.78
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/unicorn-tracks_951/index.html
***********

Book 11
Title: Unbound: How Eight Technologies Made Us Human, Transformed Society, and Brought Our World to the Brink
Category: History
Rating: One
Price: £25.52
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/unbound-how-eight-technologies-made-us-human-transformed-society-and-brought-our-world-to-the-brink_950/index.html
***********

Book 12
Title: Tsubasa: WoRLD CHRoNiCLE 2 (Tsubasa WoRLD CHRoNiCLE #2)
Category: Sequential Art
Rating: One
Price: £16.28
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/tsubasa-world-chronicle-2-tsubasa-world-chronicle-2_949/index.html
***********

Book 13
Title: Throwing Rocks at the Google Bus: How Growth Became the Enemy of Prosperity
Category: Nonfiction
Rating: Three
Price: £31.12
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/throwing-rocks-at-the-google-bus-how-growth-became-the-enemy-of-prosperity_948/index.html
***********

Book 14
Title: This One Summer
Category: Sequential Art
Rating: Four
Price: £19.49
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/this-one-summer_947/index.html
***********

Book 15
Title: Thirst
Category: Fiction
Rating: Five
Price: £17.27
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/thirst_946/index.html
***********

Book 16
Title: The Torch Is Passed: A Harding Family Story
Category: Add a comment
Rating: One
Price: £19.09
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/the-torch-is-passed-a-harding-family-story_945/index.html
***********

Book 17
Title: The Secret of Dreadwillow Carse
Category: Childrens
Rating: One
Price: £56.13
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/the-secret-of-dreadwillow-carse_944/index.html
***********

Book 18
Title: The Pioneer Woman Cooks: Dinnertime: Comfort Classics, Freezer Food, 16-Minute Meals, and Other Delicious Ways to Solve Supper!
Category: Food and Drink
Rating: One
Price: £56.41
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/the-pioneer-woman-cooks-dinnertime-comfort-classics-freezer-food-16-minute-meals-and-other-delicious-ways-to-solve-supper_943/index.html
***********

Book 19
Title: The Past Never Ends
Category: Mystery
Rating: Four
Price: £56.50
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/the-past-never-ends_942/index.html
***********

Book 20
Title: The Natural History of Us (The Fine Art of Pretending #2)
Category: Young Adult
Rating: Three
Price: £45.22
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/the-natural-history-of-us-the-fine-art-of-pretending-2_941/index.html
***********

-----------------------------
Page 3 completed.
20 books extracted from this page.
60 books extracted so far.
Time: 0.01 minutes
*****************************

========== PAGE 4 ==========

Book 1
Title: The Nameless City (The Nameless City #1)
Category: Sequential Art
Rating: Four
Price: £38.16
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/the-nameless-city-the-nameless-city-1_940/index.html
***********

Book 2
Title: The Murder That Never Was (Forensic Instincts #5)
Category: Fiction
Rating: Three
Price: £54.11
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/the-murder-that-never-was-forensic-instincts-5_939/index.html
***********

Book 3
Title: The Most Perfect Thing: Inside (and Outside) a Bird's Egg
Category: Science
Rating: Four
Price: £42.96
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/the-most-perfect-thing-inside-and-outside-a-birds-egg_938/index.html
***********

Book 4
Title: The Mindfulness and Acceptance Workbook for Anxiety: A Guide to Breaking Free from Anxiety, Phobias, and Worry Using Acceptance and Commitment Therapy
Category: Add a comment
Rating: Four
Price: £23.89
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/the-mindfulness-and-acceptance-workbook-for-anxiety-a-guide-to-breaking-free-from-anxiety-phobias-and-worry-using-acceptance-and-commitment-therapy_937/index.html
***********

Book 5
Title: The Life-Changing Magic of Tidying Up: The Japanese Art of Decluttering and Organizing
Category: Nonfiction
Rating: Three
Price: £16.77
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/the-life-changing-magic-of-tidying-up-the-japanese-art-of-decluttering-and-organizing_936/index.html
***********

Book 6
Title: The Inefficiency Assassin: Time Management Tactics for Working Smarter, Not Longer
Category: Default
Rating: Five
Price: £20.59
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/the-inefficiency-assassin-time-management-tactics-for-working-smarter-not-longer_935/index.html
***********

Book 7
Title: The Gutsy Girl: Escapades for Your Life of Epic Adventure
Category: Nonfiction
Rating: One
Price: £37.13
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/the-gutsy-girl-escapades-for-your-life-of-epic-adventure_934/index.html
***********

Book 8
Title: The Electric Pencil: Drawings from Inside State Hospital No. 3
Category: Nonfiction
Rating: One
Price: £56.06
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/the-electric-pencil-drawings-from-inside-state-hospital-no-3_933/index.html
***********

Book 9
Title: The Death of Humanity: and the Case for Life
Category: Philosophy
Rating: Four
Price: £58.11
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/the-death-of-humanity-and-the-case-for-life_932/index.html
***********

Book 10
Title: The Bulletproof Diet: Lose up to a Pound a Day, Reclaim Energy and Focus, Upgrade Your Life
Category: Health
Rating: Three
Price: £49.05
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/the-bulletproof-diet-lose-up-to-a-pound-a-day-reclaim-energy-and-focus-upgrade-your-life_931/index.html
***********

Book 11
Title: The Art Forger
Category: Add a comment
Rating: Three
Price: £40.76
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/the-art-forger_930/index.html
***********

Book 12
Title: The Age of Genius: The Seventeenth Century and the Birth of the Modern Mind
Category: History
Rating: One
Price: £19.73
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/the-age-of-genius-the-seventeenth-century-and-the-birth-of-the-modern-mind_929/index.html
***********

Book 13
Title: The Activist's Tao Te Ching: Ancient Advice for a Modern Revolution
Category: Spirituality
Rating: Five
Price: £32.24
Availability: In stock (16 available)
Book URL: https://books.toscrape.com/catalogue/the-activists-tao-te-ching-ancient-advice-for-a-modern-revolution_928/index.html
***********

Book 14
Title: Spark Joy: An Illustrated Master Class on the Art of Organizing and Tidying Up

Export the Data

In [9]:
df = pd.DataFrame(
    books_data,
    columns=[
        "Title",
        "Category",
        "Rating",
        "Price",
        "Availability",
        "Book_URL"
    ]
)
print(df.head(10))

                                               Title            Category  \
0                               A Light in the Attic              Poetry
1                                 Tipping the Velvet  Historical Fiction
2                                         Soumission             Fiction
3                                      Sharp Objects             Mystery
4              Sapiens: A Brief History of Humankind             History
5                                    The Requiem Red         Young Adult
6  The Dirty Little Secrets of Getting Your Dream...            Business
7  The Coming Woman: A Novel Based on the Life of...             Default
8  The Boys in the Boat: Nine Americans and Their...             Default
9                                    The Black Maria              Poetry

  Rating   Price             Availability  \
0  Three  £51.77  In stock (22 available)
1    One  £53.74  In stock (20 available)
2    One  £50.10  In stock (20 available)
3   Four  £47.82  In stock (20 available)
4   Five  £54.23  In stock (20 available)
5    One  £22.65  In stock (19 available)
6   Four  £33.34  In stock (19 available)
7  Three  £17.93  In stock (19 available)
8   Four  £22.60  In stock (19 available)
9    One  £52.15  In stock (19 available)

                                            Book_URL
0  https://books.toscrape.com/catalogue/a-light-i...
1  https://books.toscrape.com/catalogue/tipping-t...
2  https://books.toscrape.com/catalogue/soumissio...
3  https://books.toscrape.com/catalogue/sharp-obj...
4  https://books.toscrape.com/catalogue/sapiens-a...
5  https://books.toscrape.com/catalogue/the-requi...
6  https://books.toscrape.com/catalogue/the-dirty...
7  https://books.toscrape.com/catalogue/the-comin...
8  https://books.toscrape.com/catalogue/the-boys-...
9  https://books.toscrape.com/catalogue/the-black...

In [10]:
print(df["Book_URL"].head())

0    https://books.toscrape.com/catalogue/a-light-i...
1    https://books.toscrape.com/catalogue/tipping-t...
2    https://books.toscrape.com/catalogue/soumissio...
3    https://books.toscrape.com/catalogue/sharp-obj...
4    https://books.toscrape.com/catalogue/sapiens-a...
Name: Book_URL, dtype: object

Verify Book URLs After DataFrame Conversion

In [11]:
#print(df["Book_URL"].iloc[0])

In [12]:
for url in df["Book_URL"]:
    print(url)

https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html
https://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html
https://books.toscrape.com/catalogue/soumission_998/index.html
https://books.toscrape.com/catalogue/sharp-objects_997/index.html
https://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html
https://books.toscrape.com/catalogue/the-requiem-red_995/index.html
https://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html
https://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html
https://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html
https://books.toscrape.com/catalogue/the-black-maria_991/index.html
https://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html
https://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html
https://books.toscrape.com/catalogue/set-me-free_988/index.html
https://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html
https://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html
https://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html
https://books.toscrape.com/catalogue/olio_984/index.html
https://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html
https://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html
https://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html
https://books.toscrape.com/catalogue/in-her-wake_980/index.html
https://books.toscrape.com/catalogue/how-music-works_979/index.html
https://books.toscrape.com/catalogue/foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html
https://books.toscrape.com/catalogue/chase-me-paris-nights-2_977/index.html
https://books.toscrape.com/catalogue/black-dust_976/index.html
https://books.toscrape.com/catalogue/birdsong-a-story-in-pictures_975/index.html
https://books.toscrape.com/catalogue/americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html
https://books.toscrape.com/catalogue/aladdin-and-his-wonderful-lamp_973/index.html
https://books.toscrape.com/catalogue/worlds-elsewhere-journeys-around-shakespeares-globe_972/index.html
https://books.toscrape.com/catalogue/wall-and-piece_971/index.html
https://books.toscrape.com/catalogue/the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html
https://books.toscrape.com/catalogue/the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969/index.html
https://books.toscrape.com/catalogue/the-elephant-tree_968/index.html
https://books.toscrape.com/catalogue/the-bear-and-the-piano_967/index.html
https://books.toscrape.com/catalogue/sophies-world_966/index.html
https://books.toscrape.com/catalogue/penny-maybe_965/index.html
https://books.toscrape.com/catalogue/maude-1883-1993she-grew-up-with-the-country_964/index.html
https://books.toscrape.com/catalogue/in-a-dark-dark-wood_963/index.html
https://books.toscrape.com/catalogue/behind-closed-doors_962/index.html
https://books.toscrape.com/catalogue/you-cant-bury-them-all-poems_961/index.html
https://books.toscrape.com/catalogue/slow-states-of-collapse-poems_960/index.html
https://books.toscrape.com/catalogue/reasons-to-stay-alive_959/index.html
https://books.toscrape.com/catalogue/private-paris-private-10_958/index.html
https://books.toscrape.com/catalogue/higherselfie-wake-up-your-life-free-your-soul-find-your-tribe_957/index.html
https://books.toscrape.com/catalogue/without-borders-wanderlove-1_956/index.html
https://books.toscrape.com/catalogue/when-we-collided_955/index.html
https://books.toscrape.com/catalogue/we-love-you-charlie-freeman_954/index.html
https://books.toscrape.com/catalogue/untitled-collection-sabbath-poems-2014_953/index.html
https://books.toscrape.com/catalogue/unseen-city-the-majesty-of-pigeons-the-discreet-charm-of-snails-other-wonders-of-the-urban-wilderness_952/index.html
https://books.toscrape.com/catalogue/unicorn-tracks_951/index.html
https://books.toscrape.com/catalogue/unbound-how-eight-technologies-made-us-human-transformed-society-and-brought-our-world-to-the-brink_950/index.html
https://books.toscrape.com/catalogue/tsubasa-world-chronicle-2-tsubasa-world-chronicle-2_949/index.html
https://books.toscrape.com/catalogue/throwing-rocks-at-the-google-bus-how-growth-became-the-enemy-of-prosperity_948/index.html
https://books.toscrape.com/catalogue/this-one-summer_947/index.html
https://books.toscrape.com/catalogue/thirst_946/index.html
https://books.toscrape.com/catalogue/the-torch-is-passed-a-harding-family-story_945/index.html
https://books.toscrape.com/catalogue/the-secret-of-dreadwillow-carse_944/index.html
https://books.toscrape.com/catalogue/the-pioneer-woman-cooks-dinnertime-comfort-classics-freezer-food-16-minute-meals-and-other-delicious-ways-to-solve-supper_943/index.html
https://books.toscrape.com/catalogue/the-past-never-ends_942/index.html
https://books.toscrape.com/catalogue/the-natural-history-of-us-the-fine-art-of-pretending-2_941/index.html
https://books.toscrape.com/catalogue/the-nameless-city-the-nameless-city-1_940/index.html
https://books.toscrape.com/catalogue/the-murder-that-never-was-forensic-instincts-5_939/index.html
https://books.toscrape.com/catalogue/the-most-perfect-thing-inside-and-outside-a-birds-egg_938/index.html
https://books.toscrape.com/catalogue/the-mindfulness-and-acceptance-workbook-for-anxiety-a-guide-to-breaking-free-from-anxiety-phobias-and-worry-using-acceptance-and-commitment-therapy_937/index.html
https://books.toscrape.com/catalogue/the-life-changing-magic-of-tidying-up-the-japanese-art-of-decluttering-and-organizing_936/index.html
https://books.toscrape.com/catalogue/the-inefficiency-assassin-time-management-tactics-for-working-smarter-not-longer_935/index.html
https://books.toscrape.com/catalogue/the-gutsy-girl-escapades-for-your-life-of-epic-adventure_934/index.html
https://books.toscrape.com/catalogue/the-electric-pencil-drawings-from-inside-state-hospital-no-3_933/index.html
https://books.toscrape.com/catalogue/the-death-of-humanity-and-the-case-for-life_932/index.html
https://books.toscrape.com/catalogue/the-bulletproof-diet-lose-up-to-a-pound-a-day-reclaim-energy-and-focus-upgrade-your-life_931/index.html
https://books.toscrape.com/catalogue/the-art-forger_930/index.html
https://books.toscrape.com/catalogue/the-age-of-genius-the-seventeenth-century-and-the-birth-of-the-modern-mind_929/index.html
https://books.toscrape.com/catalogue/the-activists-tao-te-ching-ancient-advice-for-a-modern-revolution_928/index.html
https://books.toscrape.com/catalogue/spark-joy-an-illustrated-master-class-on-the-art-of-organizing-and-tidying-up_927/index.html
https://books.toscrape.com/catalogue/soul-reader_926/index.html
https://books.toscrape.com/catalogue/security_925/index.html
https://books.toscrape.com/catalogue/saga-volume-6-saga-collected-editions-6_924/index.html
https://books.toscrape.com/catalogue/saga-volume-5-saga-collected-editions-5_923/index.html
https://books.toscrape.com/catalogue/reskilling-america-learning-to-labor-in-the-twenty-first-century_922/index.html
https://books.toscrape.com/catalogue/rat-queens-vol-3-demons-rat-queens-collected-editions-11-15_921/index.html
https://books.toscrape.com/catalogue/princess-jellyfish-2-in-1-omnibus-vol-01-princess-jellyfish-2-in-1-omnibus-1_920/index.html
https://books.toscrape.com/catalogue/princess-between-worlds-wide-awake-princess-5_919/index.html
https://books.toscrape.com/catalogue/pop-gun-war-volume-1-gift_918/index.html
https://books.toscrape.com/catalogue/political-suicide-missteps-peccadilloes-bad-calls-backroom-hijinx-sordid-pasts-rotten-breaks-and-just-plain-dumb-mistakes-in-the-annals-of-american-politics_917/index.html
https://books.toscrape.com/catalogue/patience_916/index.html
https://books.toscrape.com/catalogue/outcast-vol-1-a-darkness-surrounds-him-outcast-1_915/index.html
https://books.toscrape.com/catalogue/orange-the-complete-collection-1-orange-the-complete-collection-1_914/index.html
https://books.toscrape.com/catalogue/online-marketing-for-busy-authors-a-step-by-step-guide_913/index.html
https://books.toscrape.com/catalogue/on-a-midnight-clear_912/index.html
https://books.toscrape.com/catalogue/obsidian-lux-1_911/index.html
https://books.toscrape.com/catalogue/my-paris-kitchen-recipes-and-stories_910/index.html
https://books.toscrape.com/catalogue/masks-and-shadows_909/index.html
https://books.toscrape.com/catalogue/mama-tried-traditional-italian-cooking-for-the-screwed-crude-vegan-and-tattooed_908/index.html
https://books.toscrape.com/catalogue/lumberjanes-vol-2-friendship-to-the-max-lumberjanes-5-8_907/index.html
https://books.toscrape.com/catalogue/lumberjanes-vol-1-beware-the-kitten-holy-lumberjanes-1-4_906/index.html
https://books.toscrape.com/catalogue/lumberjanes-vol-3-a-terrible-plan-lumberjanes-9-12_905/index.html
https://books.toscrape.com/catalogue/layered-baking-building-and-styling-spectacular-cakes_904/index.html
https://books.toscrape.com/catalogue/judo-seven-steps-to-black-belt-an-introductory-guide-for-beginners_903/index.html
https://books.toscrape.com/catalogue/join_902/index.html
https://books.toscrape.com/catalogue/in-the-country-we-love-my-family-divided_901/index.html

save to csv

In [13]:
df.to_csv("books_scraped.csv",index=False)
print("Data Saved")

Data Saved

Cleaning and Preprocessing Data

In [14]:
df = pd.read_csv("/content/books_scraped.csv")

In [15]:
df.head()

,Title,Category,Rating,Price,Availability,Book_URL
0,A Light in the Attic,Poetry,Three,£51.77,In stock (22 available),https://books.toscrape.com/catalogue/a-light-i...
1,Tipping the Velvet,Historical Fiction,One,£53.74,In stock (20 available),https://books.toscrape.com/catalogue/tipping-t...
2,Soumission,Fiction,One,£50.10,In stock (20 available),https://books.toscrape.com/catalogue/soumissio...
3,Sharp Objects,Mystery,Four,£47.82,In stock (20 available),https://books.toscrape.com/catalogue/sharp-obj...
4,Sapiens: A Brief History of Humankind,History,Five,£54.23,In stock (20 available),https://books.toscrape.com/catalogue/sapiens-a...

Check Data Types and Remove Unnecessary Column

In [16]:
# Check data types of all columns
print(df.dtypes)

Title           object
Category        object
Rating          object
Price           object
Availability    object
Book_URL        object
dtype: object

In [17]:
df = df.drop("Category", axis=1)

In [18]:
df.head()

,Title,Rating,Price,Availability,Book_URL
0,A Light in the Attic,Three,£51.77,In stock (22 available),https://books.toscrape.com/catalogue/a-light-i...
1,Tipping the Velvet,One,£53.74,In stock (20 available),https://books.toscrape.com/catalogue/tipping-t...
2,Soumission,One,£50.10,In stock (20 available),https://books.toscrape.com/catalogue/soumissio...
3,Sharp Objects,Four,£47.82,In stock (20 available),https://books.toscrape.com/catalogue/sharp-obj...
4,Sapiens: A Brief History of Humankind,Five,£54.23,In stock (20 available),https://books.toscrape.com/catalogue/sapiens-a...

Convert Book Ratings from Text to Numeric Values

In [20]:
df["Rating"]

0     Three
1       One
2       One
3      Four
4      Five
      ...
95      Two
96      One
97      Two
98     Five
99     Four
Name: Rating, Length: 100, dtype: object

In [21]:
df["Rating"].unique()

array(['Three', 'One', 'Four', 'Five', 'Two'], dtype=object)

In [22]:
rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

df["Rating"] = df["Rating"].map(rating_map)

In [23]:
print(df["Rating"])
print(df["Rating"].dtype)

0     3
1     1
2     1
3     4
4     5
     ..
95    2
96    1
97    2
98    5
99    4
Name: Rating, Length: 100, dtype: int64
int64

In [24]:
df.head()

,Title,Rating,Price,Availability,Book_URL
0,A Light in the Attic,3,£51.77,In stock (22 available),https://books.toscrape.com/catalogue/a-light-i...
1,Tipping the Velvet,1,£53.74,In stock (20 available),https://books.toscrape.com/catalogue/tipping-t...
2,Soumission,1,£50.10,In stock (20 available),https://books.toscrape.com/catalogue/soumissio...
3,Sharp Objects,4,£47.82,In stock (20 available),https://books.toscrape.com/catalogue/sharp-obj...
4,Sapiens: A Brief History of Humankind,5,£54.23,In stock (20 available),https://books.toscrape.com/catalogue/sapiens-a...

Convert Price from Text to Numeric Values

In [25]:
df["Price"]

0     £51.77
1     £53.74
2     £50.10
3     £47.82
4     £54.23
       ...
95    £19.92
96    £40.11
97    £53.90
98    £35.67
99    £22.00
Name: Price, Length: 100, dtype: object

In [26]:
df["Price"] = df["Price"].str.replace("£", "", regex=False).astype(float)

In [27]:
df["Price"].head()

0    51.77
1    53.74
2    50.10
3    47.82
4    54.23
Name: Price, dtype: float64

In [28]:
df.head()

,Title,Rating,Price,Availability,Book_URL
0,A Light in the Attic,3,51.77,In stock (22 available),https://books.toscrape.com/catalogue/a-light-i...
1,Tipping the Velvet,1,53.74,In stock (20 available),https://books.toscrape.com/catalogue/tipping-t...
2,Soumission,1,50.10,In stock (20 available),https://books.toscrape.com/catalogue/soumissio...
3,Sharp Objects,4,47.82,In stock (20 available),https://books.toscrape.com/catalogue/sharp-obj...
4,Sapiens: A Brief History of Humankind,5,54.23,In stock (20 available),https://books.toscrape.com/catalogue/sapiens-a...

Extract Stock Status from Availability

In [29]:
df["Availability"]

0     In stock (22 available)
1     In stock (20 available)
2     In stock (20 available)
3     In stock (20 available)
4     In stock (20 available)
               ...
95    In stock (16 available)
96    In stock (16 available)
97    In stock (16 available)
98    In stock (16 available)
99    In stock (16 available)
Name: Availability, Length: 100, dtype: object

In [30]:
df['Availability'].value_counts()

Availability
In stock (16 available)    56
In stock (19 available)    23
In stock (18 available)    11
In stock (17 available)     5
In stock (20 available)     4
In stock (22 available)     1
Name: count, dtype: int64

In [31]:
df['Availability'].unique()

array(['In stock (22 available)', 'In stock (20 available)',
       'In stock (19 available)', 'In stock (18 available)',
       'In stock (17 available)', 'In stock (16 available)'], dtype=object)

In [32]:
df["in_stock"] = df["Availability"].str.contains("In stock")

In [33]:
df['in_stock'].value_counts()

in_stock
True    100
Name: count, dtype: int64

In [34]:
df['in_stock'].unique()

array([ True])

In [35]:
df.head()

,Title,Rating,Price,Availability,Book_URL,in_stock
0,A Light in the Attic,3,51.77,In stock (22 available),https://books.toscrape.com/catalogue/a-light-i...,True
1,Tipping the Velvet,1,53.74,In stock (20 available),https://books.toscrape.com/catalogue/tipping-t...,True
2,Soumission,1,50.10,In stock (20 available),https://books.toscrape.com/catalogue/soumissio...,True
3,Sharp Objects,4,47.82,In stock (20 available),https://books.toscrape.com/catalogue/sharp-obj...,True
4,Sapiens: A Brief History of Humankind,5,54.23,In stock (20 available),https://books.toscrape.com/catalogue/sapiens-a...,True

Remove the Original Availability Column

In [36]:
df = df.drop(columns=["Availability"])

In [37]:
df.head()

,Title,Rating,Price,Book_URL,in_stock
0,A Light in the Attic,3,51.77,https://books.toscrape.com/catalogue/a-light-i...,True
1,Tipping the Velvet,1,53.74,https://books.toscrape.com/catalogue/tipping-t...,True
2,Soumission,1,50.10,https://books.toscrape.com/catalogue/soumissio...,True
3,Sharp Objects,4,47.82,https://books.toscrape.com/catalogue/sharp-obj...,True
4,Sapiens: A Brief History of Humankind,5,54.23,https://books.toscrape.com/catalogue/sapiens-a...,True

Check Final Data Types and Save Cleaned Data

In [38]:
print(df.dtypes)

Title        object
Rating        int64
Price       float64
Book_URL     object
in_stock       bool
dtype: object

In [39]:
df.to_csv("books_scraped_cleaned.csv", index=False)

print("Cleaned data saved successfully!")

Cleaned data saved successfully!

Load the CSV into SQLite

In [40]:
# 1. Connect to SQLite database
conn = sqlite3.connect("books.db")

In [41]:
# 2. Load CSV
df = pd.read_csv("books_scraped_cleaned.csv")

In [42]:
# 3. Save CSV data into SQLite table
df.to_sql("books", conn, if_exists="replace", index=False)

print("CSV loaded into SQLite successfully!")

CSV loaded into SQLite successfully!

In [43]:
print(pd.read_sql_query("PRAGMA table_info(books);", conn))

   cid      name     type  notnull dflt_value  pk
0    0     Title     TEXT        0       None   0
1    1    Rating  INTEGER        0       None   0
2    2     Price     REAL        0       None   0
3    3  Book_URL     TEXT        0       None   0
4    4  in_stock  INTEGER        0       None   0

1. Average price for each rating

In [44]:
query = """
    SELECT Rating, AVG(Price) AS Avg_Price
    FROM books
    GROUP BY Rating
    ORDER BY Rating;
"""

result = pd.read_sql_query(query, conn)
print(result)

   Rating  Avg_Price
0       1  35.519545
1       2  35.909474
2       3  36.839091
3       4  33.981667
4       5  30.012105

2. The 5 most expensive books rated 4 or 5

In [45]:
query = """
    SELECT Title, Rating, Price
    FROM books
    WHERE Rating IN (4, 5)
    ORDER BY Price DESC
    LIMIT 5;
"""

result = pd.read_sql_query(query, conn)
print(result)

                                               Title  Rating  Price
0       The Death of Humanity: and the Case for Life       4  58.11
1                                The Past Never Ends       4  56.50
2              Sapiens: A Brief History of Humankind       5  54.23
3  Scott Pilgrim's Precious Little Life (Scott Pi...       5  52.29
4                                Behind Closed Doors       4  52.22

3. How many books are out of stock, per rating

In [56]:
##This two cells only to check that the third quiry work without any Error
# test_query = """
# INSERT INTO books (Title, Rating, Price, Book_URL, in_stock)
# VALUES ('Test Out of Stock Book', 4, 100.00, 'test_url', 0);
# """

# conn.execute(test_query)
# conn.commit()

In [51]:
# delete_query = """
# DELETE FROM books
# WHERE Title IN ('Test Out of Stock Book', 'Test Out of Stock Book 2');
# """

# conn.execute(delete_query)
# conn.commit()

# print("Test rows deleted successfully!")

Test rows deleted successfully!

In [52]:
query = """
    SELECT Rating, COUNT(*) AS Out_Of_Stock_Count
    FROM books
    WHERE in_stock = 0
    GROUP BY Rating
    ORDER BY Rating;
"""

result = pd.read_sql_query(query, conn)
print(result)

Empty DataFrame
Columns: [Rating, Out_Of_Stock_Count]
Index: []

Check if There Are No Out-of-Stock Books

In [47]:
print(df["in_stock"].value_counts())

in_stock
True    100
Name: count, dtype: int64

In [48]:
query = """
SELECT in_stock, COUNT(*) AS Count
FROM books
GROUP BY in_stock;
"""

result = pd.read_sql_query(query, conn)
print(result)

   in_stock  Count
0         1    100

In [53]:
query_check = "SELECT DISTINCT in_stock FROM books;"
print(pd.read_sql_query(query_check, conn))

   in_stock
0         1

In [54]:
query_in_stock = "SELECT COUNT(*) AS Total_In_Stock FROM books WHERE in_stock = 1;"
print(pd.read_sql_query(query_in_stock, conn))

   Total_In_Stock
0             100

Create and Save SQL Queries to a File

In [55]:
with open("queries.sql", "w", encoding="utf-8") as file:
    file.write("")

In [58]:
queries = """
-- 1. Average price for each rating
SELECT Rating, AVG(Price) AS Avg_Price
FROM books
GROUP BY Rating
ORDER BY Rating;

-- 2. The 5 most expensive books rated 4 or 5
SELECT Title, Rating, Price
FROM books
WHERE Rating IN (4, 5)
ORDER BY Price DESC
LIMIT 5;

-- 3. How many books are out of stock, per rating
SELECT Rating, COUNT(*) AS Out_Of_Stock_Count
FROM books
WHERE in_stock = 0
GROUP BY Rating
ORDER BY Rating;
"""

In [59]:
with open("queries.sql", "w", encoding="utf-8") as file:
    file.write(queries)

Read and Verify SQL Queries File

In [60]:
with open("queries.sql", "r", encoding="utf-8") as file:
    queries = file.read()

print(queries)

-- 1. Average price for each rating
SELECT Rating, AVG(Price) AS Avg_Price
FROM books
GROUP BY Rating
ORDER BY Rating;

-- 2. The 5 most expensive books rated 4 or 5
SELECT Title, Rating, Price
FROM books
WHERE Rating IN (4, 5)
ORDER BY Price DESC
LIMIT 5;

-- 3. How many books are out of stock, per rating
SELECT Rating, COUNT(*) AS Out_Of_Stock_Count
FROM books
WHERE in_stock = 0
GROUP BY Rating
ORDER BY Rating;

In [61]:
conn.close()